### ISSUE TITLE
Router use private properties which disable any route listing

### ISSUE THREAD

**Issue by smalot** [igniphp/framework#10]
I'm looking for exposing all available routes for debug purpose or may be to create a swagger file.
Because route collection is a private property, I'm not able to override the Router class to handle it.

Can you change property scope for "protected" ?

**Comment by smalot** [comment]
Could you too create an interface for the `Router` ? Based on the fact that it can be overriden using depndency injection.

**Comment by dkraczkowski** [comment]
@smalot I have created PR with proposed `Route` and `Router` interfaces. Please review if you can.
https://github.com/igniphp/framework/pull/16
