### ISSUE TITLE
Howto integrate `symfony/dependency-injection` instead of internal DI

### ISSUE THREAD

**Issue by smalot** [igniphp/framework#11]
Your current dependency injection implementation allow to use the symfony/dependency-injection package.

But It could be interesting to explain how to integrate it properly into the project in the documentation:
- compilation
- compiling pass
- tags

**Comment by dkraczkowski** [comment]
@smalot https://github.com/igniphp/framework/blob/ad4964b669f36407fa75a89f5a087082d570e7b6/docs/README.md#working-with-containers I hope this helps.

**Comment by smalot** [comment]
Many thanks !!
