### ISSUE TITLE
Last router method with same name is overwrite previous with other http method

### ISSUE THREAD

**Issue by roquie** [igniphp/framework#28]
How to reproduce?
```php
<?php
// Setup server
$server = new HttpServer(new Configuration('0.0.0.0', 8080));
// Setup application and routes
$application = new HttpApplication();
$application->put('/user/{id}', function (ServerRequestInterface $request) : ResponseInterface {
    return Response::asText("updated");
});
$application->delete('/user/{id}', function (ServerRequestInterface $request) : ResponseInterface {
    return Response::asText("destroyed");
});
// Run the server, it should listen on localhost:8080
$application->run($server);
```

Two routes contains same name and latest route (with delete method) is overwrite the previous. This leads to the following error:
```
This uri `/user/5` allows only DELETE http methods.
```

It's a bug.

**Comment by dkraczkowski** [comment]
@roquie Thanks for rising it, it will get fixed very soon.

**Comment by roquie** [comment]
@dkraczkowski pls, accept the PR, https://github.com/igniphp/network/pull/5

And draft new release for composer.

**Comment by dkraczkowski** [comment]
Note: Seems like the problem is within the route naming, the routes get overridden because I am reusing the same name to register the route. I will need to tweak it a bit with help of currently used symfony router

**Comment by roquie** [comment]
It has done. Just merge PR as soon as possible.
https://github.com/igniphp/network/pull/7

**Comment by dkraczkowski** [comment]
@roquie Thanks for help with this one.
