### ISSUE TITLE
In tests not possible to pass attributes by example

### ISSUE THREAD

**Issue by roquie** [igniphp/framework#29]
https://github.com/igniphp/framework/tree/master/docs#testing

In the following example, `name` attribute does not correctly passing to `ServerRequest` object.
```php
public function testWelcome(): void
    {
        $controller = new WelcomeUserController();
        $response = $controller(new ServerRequest('/hi/Tom'));
        
        self::assertSame('Hi Tom!', (string) $response->getBody());
        self::assertSame(200, $response->getStatusCode());
    }
```

Solution:

```php
public function testWelcome(): void
    {
        $controller = new WelcomeUserController();
        $response = $controller((new ServerRequest('/hi/Tom'))->withAttribute('name', 'Tom'));
        
        self::assertSame('Hi Tom!', (string) $response->getBody());
        self::assertSame(200, $response->getStatusCode());
    }
```

P.S. This is a WIP issue. I will update it soon.

**Comment by dkraczkowski** [comment]
@roquie You are right, I will fix the example soon.

**Comment by roquie** [comment]
It's normal when it passes not automatically? The solution in docs is more pretty and short :)

**Comment by dkraczkowski** [comment]
@roquie Yeah its normal because it does not go through the framework, so you are actually passing just a request object and you get the same one in the controller.

**Comment by roquie** [comment]
Hmm, maybe set up something for testing?
