### ISSUE TITLE
Switch router to Symfony

### ISSUE THREAD

**Issue by garak** [igniphp/framework#3]
According to [Symfony blog](https://symfony.com/blog/new-in-symfony-4-1-fastest-php-router), its router is now faster than FastRoute.
You should consider a change in your requirements.
As alternative, you should remove mention to "fastest router" in README.

**Comment by dkraczkowski** [comment]
@garak I have started working on implementation ([symfony_routing](https://github.com/igniphp/framework/tree/symfony_routing) branch), but there is a problem - symfony router does not support [optional parts](https://github.com/nikic/FastRoute#defining-routes)  :<. I am wondering whether it is worth supporting this feature. Any guess?

**Comment by garak** [comment]
I didn't try to use routing outside Symfony framework, but inside framework itself such option is present (so I guess it's possible somehow)

**Comment by dkraczkowski** [comment]
Could you please provide me equivalent  of the following route:
`/some[/optional[/{route}]]`

**Comment by garak** [comment]
See http://symfony.com/doc/current/routing/optional_placeholders.html

**Comment by dkraczkowski** [comment]
Have seen it, and it looks like you can have optional placeholders (if you define default values) but not optional parts of the route.

**Comment by garak** [comment]
I see. To fulfill your example, you need to define 2 routes

**Comment by dkraczkowski** [comment]
precisely! But if none is using this functionality maybe its worth switching to symfony-router.

**Comment by dkraczkowski** [comment]
https://github.com/igniphp/framework/pull/8

**Comment by dkraczkowski** [comment]
Fixed.
