### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by lezhnev74** [igniphp/framework#5]
From the documentation, it is not clear how to handle exception occurred in business logic.
Since Swool does not support `set_exception_handler` function, where is the central error handler in igni framework and what is the preferred way to handle exceptions and provide pretty output to the client?

Thanks!

p.s.
I managed to find this `ErrorMiddleware` which by default catches any exception (and converts errors to exceptions). I guess error handling is something to be done via that middleware, right?

**Comment by dkraczkowski** [comment]
@lezhnev74 Hello, all thrown and unhandled exceptions in your application are by default handled by`\Igni\Http\Middleware\ErrorMiddleware` class which returns 500 response with error message provided by the exception.

If you would like to have one central place for all your business exceptions the preferred way is to define psr middleware, for example:
```php
<?php
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;

final class MyErrorHandler implements MiddlewareInterface
{
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        try {
            // Allow rest of middleware pipe to do its job
            $response = $next->handle($request);
        }  catch (TheExceptionTypeYouWouldLikeToHandle $exception) {
            $response = <here generate your psr response>;
        }
        return $response;
    }
}
```

The defined middleware should be also added to your application:
```
$application->use(new MyErrorHandler());
```

please also refer to this [link](https://github.com/igniphp/framework/blob/master/docs/README.md#middleware)

**Comment by dkraczkowski** [comment]
Optionally you can define your error handler as a closure function and pass it into `use` method:
```php
$application->use(function(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface {
    try {
        // Allow rest of middleware pipe to do its job
        $response = $next->handle($request);
    }  catch (TheExceptionTypeYouWouldLikeToHandle $exception) {
        $response = <here generate your psr response>;
    }
    return $response;
});
```

**Comment by dkraczkowski** [comment]
@lezhnev74 Does it help?

**Comment by lezhnev74** [comment]
Yes! Looks clear now. Thank you @dkraczkowski !
